#!/bin/bash

CONFIG_SOURCE="/opt/nut-config"
export CONFIG_SOURCE

CONFIG_DEST="/etc/nut"
export CONFIG_DEST

echo "Copying configurations from ${CONFIG_SOURCE} to ${CONFIG_DEST}..."

find $CONFIG_SOURCE -name "*.conf" -exec cp '{}' $CONFIG_DEST \;
find $CONFIG_SOURCE -name "*.html" -exec cp '{}' $CONFIG_DEST \;

echo "Restarting services..."

upsdrvctl start
/etc/init.d/nut-server restart

echo "Ready on port 3493"
tail -F /dev/null
